<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hotelchain extends \App\Entity\Hotelchain implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'idHotelchain', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'hotelchainName', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'hotelchainStaff', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'hotelchainDescription', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'phone'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'idHotelchain', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'hotelchainName', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'hotelchainStaff', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'hotelchainDescription', '' . "\0" . 'App\\Entity\\Hotelchain' . "\0" . 'phone'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hotelchain $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdHotelchain(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdHotelchain();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdHotelchain', []);

        return parent::getIdHotelchain();
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelchainName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelchainName', []);

        return parent::getHotelchainName();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelchainName(string $hotelchainName): \App\Entity\Hotelchain
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelchainName', [$hotelchainName]);

        return parent::setHotelchainName($hotelchainName);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelchainStaff(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelchainStaff', []);

        return parent::getHotelchainStaff();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelchainStaff(string $hotelchainStaff): \App\Entity\Hotelchain
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelchainStaff', [$hotelchainStaff]);

        return parent::setHotelchainStaff($hotelchainStaff);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelchainDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelchainDescription', []);

        return parent::getHotelchainDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelchainDescription(string $hotelchainDescription): \App\Entity\Hotelchain
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelchainDescription', [$hotelchainDescription]);

        return parent::setHotelchainDescription($hotelchainDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone(string $phone): \App\Entity\Hotelchain
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

}
