<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Car extends \App\Entity\Car implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'idCar', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'namecar', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carnumber', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carcolor', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carbrand', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carimage', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'rentstatus', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'fkAgency'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'idCar', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'namecar', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carnumber', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carcolor', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carbrand', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'carimage', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'rentstatus', '' . "\0" . 'App\\Entity\\Car' . "\0" . 'fkAgency'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Car $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCar(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCar();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCar', []);

        return parent::getIdCar();
    }

    /**
     * {@inheritDoc}
     */
    public function getNamecar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNamecar', []);

        return parent::getNamecar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNamecar(?string $namecar): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNamecar', [$namecar]);

        return parent::setNamecar($namecar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarnumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarnumber', []);

        return parent::getCarnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarnumber(string $carnumber): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarnumber', [$carnumber]);

        return parent::setCarnumber($carnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarcolor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarcolor', []);

        return parent::getCarcolor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarcolor(string $carcolor): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarcolor', [$carcolor]);

        return parent::setCarcolor($carcolor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarbrand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarbrand', []);

        return parent::getCarbrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarbrand(string $carbrand): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarbrand', [$carbrand]);

        return parent::setCarbrand($carbrand);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarimage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarimage', []);

        return parent::getCarimage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarimage(?string $carimage): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarimage', [$carimage]);

        return parent::setCarimage($carimage);
    }

    /**
     * {@inheritDoc}
     */
    public function getRentstatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRentstatus', []);

        return parent::getRentstatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRentstatus(bool $rentstatus): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRentstatus', [$rentstatus]);

        return parent::setRentstatus($rentstatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkAgency(): ?\App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkAgency', []);

        return parent::getFkAgency();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkAgency(?\App\Entity\Agency $fkAgency): \App\Entity\Car
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkAgency', [$fkAgency]);

        return parent::setFkAgency($fkAgency);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $carimage = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$carimage]);

        return parent::setImageFile($carimage);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
