<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agency extends \App\Entity\Agency implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'idAgency', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'nameagency', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'agencyphonenumber', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'agencylocation', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'agencydescription', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'numberofcars', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'numberofavailablecars', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'imageagency', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'nbrlike'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'idAgency', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'nameagency', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'agencyphonenumber', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'agencylocation', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'agencydescription', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'numberofcars', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'numberofavailablecars', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'imageagency', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Agency' . "\0" . 'nbrlike'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agency $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdAgency(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAgency();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAgency', []);

        return parent::getIdAgency();
    }

    /**
     * {@inheritDoc}
     */
    public function getNameagency(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNameagency', []);

        return parent::getNameagency();
    }

    /**
     * {@inheritDoc}
     */
    public function setNameagency(string $nameagency): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNameagency', [$nameagency]);

        return parent::setNameagency($nameagency);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencyphonenumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencyphonenumber', []);

        return parent::getAgencyphonenumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencyphonenumber(string $agencyphonenumber): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencyphonenumber', [$agencyphonenumber]);

        return parent::setAgencyphonenumber($agencyphonenumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencylocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencylocation', []);

        return parent::getAgencylocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencylocation(string $agencylocation): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencylocation', [$agencylocation]);

        return parent::setAgencylocation($agencylocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencydescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencydescription', []);

        return parent::getAgencydescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencydescription(string $agencydescription): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencydescription', [$agencydescription]);

        return parent::setAgencydescription($agencydescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberofcars(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberofcars', []);

        return parent::getNumberofcars();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberofcars(int $numberofcars): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberofcars', [$numberofcars]);

        return parent::setNumberofcars($numberofcars);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberofavailablecars(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberofavailablecars', []);

        return parent::getNumberofavailablecars();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberofavailablecars(int $numberofavailablecars): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberofavailablecars', [$numberofavailablecars]);

        return parent::setNumberofavailablecars($numberofavailablecars);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageagency(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageagency', []);

        return parent::getImageagency();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageagency(?string $imageagency): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageagency', [$imageagency]);

        return parent::setImageagency($imageagency);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrlike(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrlike', []);

        return parent::getNbrlike();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrlike(?int $nbrlike): \App\Entity\Agency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrlike', [$nbrlike]);

        return parent::setNbrlike($nbrlike);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $imageagency = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageagency]);

        return parent::setImageFile($imageagency);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
