<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Room extends \App\Entity\Room implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'idRoom', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'roomType', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'roomCapacity', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'isempty', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'nbrroom', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'fkHotel', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'idRoom', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'roomType', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'roomCapacity', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'isempty', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'nbrroom', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'fkHotel', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Room' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Room $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdRoom(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdRoom();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRoom', []);

        return parent::getIdRoom();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomType', []);

        return parent::getRoomType();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomType(string $roomType): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomType', [$roomType]);

        return parent::setRoomType($roomType);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomCapacity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomCapacity', []);

        return parent::getRoomCapacity();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomCapacity(string $roomCapacity): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomCapacity', [$roomCapacity]);

        return parent::setRoomCapacity($roomCapacity);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsempty(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsempty', []);

        return parent::getIsempty();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsempty(bool $isempty): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsempty', [$isempty]);

        return parent::setIsempty($isempty);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrroom(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrroom', []);

        return parent::getNbrroom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrroom(int $nbrroom): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrroom', [$nbrroom]);

        return parent::setNbrroom($nbrroom);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkHotel(): ?\App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkHotel', []);

        return parent::getFkHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkHotel(?\App\Entity\Hotel $fkHotel): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkHotel', [$fkHotel]);

        return parent::setFkHotel($fkHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(float $price): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(string $image): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getBooks(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBooks', []);

        return parent::getBooks();
    }

    /**
     * {@inheritDoc}
     */
    public function addBook(\App\Entity\Book $book): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBook', [$book]);

        return parent::addBook($book);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBook(\App\Entity\Book $book): \App\Entity\Room
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBook', [$book]);

        return parent::removeBook($book);
    }

}
