<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hotel extends \App\Entity\Hotel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'idHotel', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelName', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelStaff', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelLocation', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelPhone', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelDescription', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelImg', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'fkHotelchain', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'rating'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'idHotel', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelName', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelStaff', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelLocation', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelPhone', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelDescription', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'hotelImg', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'fkHotelchain', '' . "\0" . 'App\\Entity\\Hotel' . "\0" . 'rating'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hotel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdHotel(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdHotel();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdHotel', []);

        return parent::getIdHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelName', []);

        return parent::getHotelName();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelName(string $hotelName): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelName', [$hotelName]);

        return parent::setHotelName($hotelName);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelStaff(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelStaff', []);

        return parent::getHotelStaff();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelStaff(string $hotelStaff): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelStaff', [$hotelStaff]);

        return parent::setHotelStaff($hotelStaff);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelLocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelLocation', []);

        return parent::getHotelLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelLocation(string $hotelLocation): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelLocation', [$hotelLocation]);

        return parent::setHotelLocation($hotelLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelPhone', []);

        return parent::getHotelPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelPhone(string $hotelPhone): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelPhone', [$hotelPhone]);

        return parent::setHotelPhone($hotelPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelDescription', []);

        return parent::getHotelDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelDescription(string $hotelDescription): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelDescription', [$hotelDescription]);

        return parent::setHotelDescription($hotelDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelImg(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelImg', []);

        return parent::getHotelImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelImg(?string $hotelImg): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelImg', [$hotelImg]);

        return parent::setHotelImg($hotelImg);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkHotelchain(): ?\App\Entity\Hotelchain
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkHotelchain', []);

        return parent::getFkHotelchain();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkHotelchain(?\App\Entity\Hotelchain $fkHotelchain): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkHotelchain', [$fkHotelchain]);

        return parent::setFkHotelchain($fkHotelchain);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating(int $rating): \App\Entity\Hotel
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

}
