#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /hotels
    controller: App\Controller\HotelController::indexFront

indexFront:
    path: /hotelroom/{idHotel}
    controller: App\Controller\RoomController::indexFront
