<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDCjWepv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDCjWepv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDCjWepv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDCjWepv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDCjWepv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DCjWepv',
    'container.build_id' => 'ad7b7a2b',
    'container.build_time' => 1650844399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDCjWepv');
