<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUoxG2Ky\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUoxG2Ky/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUoxG2Ky.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUoxG2Ky\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUoxG2Ky\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UoxG2Ky',
    'container.build_id' => '422e67b3',
    'container.build_time' => 1650729653,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUoxG2Ky');
